import type { CSSProperties } from 'react'
import { Fades } from '../../components/animate-ui/primitives/effects/fade'
import { SlidingNumber } from '../../components/animate-ui/primitives/texts/sliding-number'
import { useI18n, type Locale } from '../../shared/i18n'
import type { MonthlySummary } from './owner-api'
import './MonthlySummaryPanel.css'

type Props = { summary: MonthlySummary }
type Copy = Readonly<Record<Locale, string>>
const copy = (ja:string,en:string):Copy => ({ja,en})
const percentage=(value:number,total:number)=>total<=0?0:Math.min(100,Math.max(0,Math.round(value/total*100)))
function Metric({label,value,note,suffix}:{label:string;value:number;note:string;suffix:string}){return <div className="monthly-summary-panel__metric-row"><div><strong>{label}</strong><span>{note}</span></div><b><SlidingNumber number={value} fromNumber={value} initiallyStable inView inViewOnce />{suffix}</b></div>}

export function MonthlySummaryPanel({summary}:Props){
 const {locale,text,formatDate,formatNumber}=useI18n(); const count=(n:number)=>locale==='ja'?`${formatNumber(n)}件`:`${formatNumber(n)} ${n===1?'response':'responses'}`
 const date=new Date(`${summary.period_start}T00:00:00+09:00`); const label=Number.isNaN(date.getTime())?text(copy('今月','This month')):formatDate(date,{year:'numeric',month:'long',timeZone:'Asia/Tokyo'})
 const completion=Math.min(100,Math.max(0,summary.completion_rate)), generation=percentage(summary.generation_succeeded,summary.completed), handoff=percentage(summary.google_handoffs,summary.completed)
 const total=Object.values(summary.rating_distribution).reduce((a,b)=>a+b,0), tone=summary.started_change>0?'positive':summary.started_change<0?'negative':'neutral'
 const comparison=summary.started_change===0
  ? (locale==='ja'?`開始数は前月と同じ${count(summary.started)}でした。`:`Starts were unchanged from last month at ${count(summary.started)}.`)
  : (locale==='ja'?`開始数は前月の${count(summary.previous_started)}から${count(Math.abs(summary.started_change))}${summary.started_change>0?'増えました':'減りました'}。今月は${count(summary.started)}です。`:`Starts ${summary.started_change>0?'increased':'decreased'} by ${count(Math.abs(summary.started_change))}, from ${count(summary.previous_started)} last month to ${count(summary.started)} this month.`)
 return <section className="monthly-summary-panel" aria-label={locale==='ja'?`${label}の月次サマリー`:`Monthly summary for ${label}`}>
  <header className="monthly-summary-panel__header"><span className="monthly-summary-panel__period">{label}</span><span className={`monthly-summary-panel__change monthly-summary-panel__change--${tone}`}>{text(copy('前月比','vs. previous month'))} {summary.started_change>0?'+':''}{formatNumber(summary.started_change)}{locale==='ja'?'件':''}</span></header>
  <div className="monthly-summary-panel__overview"><section className="monthly-summary-panel__completion" aria-labelledby="monthly-summary-completion-title"><span id="monthly-summary-completion-title">{text(copy('回答完了率','Completion rate'))}</span><div className="monthly-summary-panel__completion-value"><strong><SlidingNumber number={summary.completion_rate} fromNumber={summary.completion_rate} initiallyStable inView inViewOnce /></strong><small>%</small></div><div className="monthly-summary-panel__progress" role="progressbar" aria-label={text(copy('回答完了率','Completion rate'))} aria-valuemin={0} aria-valuemax={100} aria-valuenow={completion}><span style={{'--monthly-summary-progress':`${completion}%`} as CSSProperties}/></div><p>{locale==='ja'?`${count(summary.started)}の開始のうち、${count(summary.completed)}が最後まで完了しました。`:`${count(summary.completed)} were completed out of ${count(summary.started)} started.`}</p></section>
  <section className="monthly-summary-panel__flow" aria-labelledby="monthly-summary-flow-title"><h3 id="monthly-summary-flow-title">{text(copy('今月の流れ','This month’s funnel'))}</h3><div className="monthly-summary-panel__metric-list"><Fades asChild inView inViewOnce holdDelay={60}><Metric suffix={locale==='ja'?'件':''} label={text(copy('アンケート開始','Survey starts'))} value={summary.started} note={text(copy('QRコードから回答を開始','Started from the QR code'))}/><Metric suffix={locale==='ja'?'件':''} label={text(copy('回答完了','Completed responses'))} value={summary.completed} note={locale==='ja'?`開始した方の${summary.completion_rate}%`:`${summary.completion_rate}% of starts`}/><Metric suffix={locale==='ja'?'件':''} label={text(copy('口コミ文を作成','Reviews generated'))} value={summary.generation_succeeded} note={locale==='ja'?`完了した方の${generation}%`:`${generation}% of completions`}/><Metric suffix={locale==='ja'?'件':''} label={text(copy('Googleへ移動','Google handoffs'))} value={summary.google_handoffs} note={locale==='ja'?`完了した方の${handoff}%`:`${handoff}% of completions`}/></Fades></div></section></div>
  <div className="monthly-summary-panel__details"><section className="monthly-summary-panel__ratings" aria-labelledby="monthly-summary-ratings-title"><div className="monthly-summary-panel__section-title"><div><h3 id="monthly-summary-ratings-title">{text(copy('評価の傾向','Rating trends'))}</h3><p>{total>0?(locale==='ja'?`${count(total)}の評価を集計`:`Based on ${count(total)}`):text(copy('評価データはまだありません','No rating data yet'))}</p></div><div className="monthly-summary-panel__rating-average" aria-label={`${text(copy('平均評価','Average rating'))} ${summary.average_rating??text(copy('未集計','not available'))}`}><span>{text(copy('平均','Average'))}</span><strong>{summary.average_rating===null?'—':formatNumber(summary.average_rating,{minimumFractionDigits:1,maximumFractionDigits:1})}</strong>{summary.average_rating===null?null:<small>/ 5</small>}</div></div>{total>0?<div className="monthly-summary-panel__rating-bars">{[5,4,3,2,1].map(r=>{const n=summary.rating_distribution[String(r)]??0;return <div className="monthly-summary-panel__rating-row" key={r}><span>{r}</span><div aria-hidden="true"><i style={{width:`${percentage(n,total)}%`}}/></div><b>{count(n)}</b></div>})}</div>:<div className="monthly-summary-panel__rating-empty">{text(copy('回答に評価が含まれると、ここに分布が表示されます。','The rating distribution will appear here once responses include ratings.'))}</div>}</section>
  <section className="monthly-summary-panel__comparison" aria-labelledby="monthly-summary-comparison-title"><span>{text(copy('前月との比較','Compared with last month'))}</span><h3 id="monthly-summary-comparison-title">{summary.started_change>0?text(copy('回答の動きが増えています','Response activity is increasing')):summary.started_change<0?text(copy('回答の動きを確認しましょう','Review response activity')):text(copy('前月と同じペースです','The pace is unchanged'))}</h3><p>{comparison}</p><dl><div><dt>{text(copy('前月','Last month'))}</dt><dd>{count(summary.previous_started)}</dd></div><div><dt>{text(copy('今月','This month'))}</dt><dd>{count(summary.started)}</dd></div></dl></section></div>
 </section>
}
